#if !defined(SDB_TABLE_CONSTANTS_H)
#define SDB_TABLE_CONSTANTS_H

#define COLUMN_ID_SIZE 4
#define COLUMN_USERNAME_SIZE 32
#define COLUMN_EMAIL_SIZE 256

#define TABLE_MAX_PAGES 100
#define PAGE_SIZE 4096

#define ROW_SIZE (COLUMN_ID_SIZE + COLUMN_USERNAME_SIZE + COLUMN_EMAIL_SIZE)

#define ROWS_PER_PAGE (PAGE_SIZE / ROW_SIZE)
#define TABLE_MAX_ROWS (ROWS_PER_PAGE * TABLE_MAX_PAGES)

#endif // SDB_TABLE_CONSTANTS_H
